defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "photo"
    values:
      layout: "gallery"
collections_dir: collections
collections:
  photo:
    output: true
